name: habitat
channels:
  - defaults
  - conda-forge
  - aihabitat
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - attrs=25.3.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2025.8.3
  - cmake=3.14.0
  - colorama=0.4.6
  - comm=0.2.3
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.3
  - freetype=2.14.1
  - gettext=0.21.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - habitat-sim-mutex=1.0
  - icu=73.1
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jansson=2.14
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - libkrb5=1.22.1
  - liblapack=3.11.0
  - libllvm14=14.0.6
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.54
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.6.0
  - packaging=26.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.3
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pyzmq=27.0.2
  - quaternion=2023.0.4
  - readline=8.3
  - rhash=1.4.3
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=3.0.5
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025c
  - wcwidth=0.2.13
  - wheel=0.45.1
  - withbullet=2.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - habitat-sim==0.3.3
      - imageio-ffmpeg==0.6.0
      - opencv-python==4.10.0.84
      - pillow==10.4.0
prefix: /home/testunot/miniconda3/envs/habitat
