name: openpi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - attrs==25.4.0
      - augmax==0.4.1
      - av==16.1.0
      - beartype==0.19.0
      - beautifulsoup4==4.14.3
      - blinker==1.9.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cmake==4.2.1
      - cryptography==46.0.4
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - datasets==4.5.0
      - decorator==5.2.1
      - deepdiff==8.6.1
      - diffusers==0.36.0
      - dill==0.4.0
      - dm-control==1.0.36
      - dm-env==1.6
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - donfig==0.8.1.post1
      - draccus==0.10.0
      - einops==0.8.2
      - equinox==0.13.4
      - etils==1.13.0
      - evdev==1.9.3
      - farama-notifications==0.0.4
      - filelock==3.20.3
      - flask==3.1.2
      - flatbuffers==25.12.19
      - flax==0.10.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gcsfs==2025.10.0
      - gdown==5.2.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - google-api-core==2.29.0
      - google-auth==2.48.0
      - google-auth-oauthlib==1.2.4
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.9.0
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - gym-aloha==0.1.3
      - gymnasium==0.29.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - humanize==4.15.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - itsdangerous==2.2.0
      - jax==0.5.3
      - jax-cuda12-pjrt==0.5.3
      - jax-cuda12-plugin==0.5.3
      - jaxlib==0.5.3
      - jaxtyping==0.2.36
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - labmaze==1.0.6
      - lerobot==0.1.0
      - llvmlite==0.46.0
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-collections==1.0.0
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mujoco==3.4.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numba==0.63.1
      - numcodecs==0.16.5
      - numpy==1.26.4
      - numpydantic==1.7.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - openpi==0.1.0
      - openpi-client==0.1.0
      - opt-einsum==3.4.0
      - optax==0.2.7
      - orbax-checkpoint==0.11.13
      - orderly-set==5.5.0
      - pandas==3.0.0
      - pfzy==0.3.4
      - pillow==12.1.0
      - platformdirs==4.5.1
      - polars==1.38.1
      - polars-runtime-32==1.38.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.27.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pyarrow==23.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pymunk==7.2.0
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - pyzmq==27.1.0
      - regex==2026.1.15
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rerun-sdk==0.23.1
      - rich==14.3.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - scipy==1.17.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.52.0
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.3
      - svgwrite==1.4.3
      - sympy==1.14.0
      - tensorstore==0.1.74
      - termcolor==3.3.0
      - tokenizers==0.21.4
      - toml==0.10.2
      - torch==2.10.0
      - torchcodec==0.10.0
      - torchvision==0.25.0
      - tqdm==4.67.3
      - tqdm-loggable==0.2
      - transformers==4.48.1
      - tree==0.2.4
      - treescope==0.1.10
      - triton==3.6.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tyro==1.0.6
      - urllib3==2.6.3
      - wadler-lindig==0.1.7
      - wandb==0.24.2
      - wcwidth==0.6.0
      - websockets==16.0
      - werkzeug==3.1.5
      - wrapt==2.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zarr==3.1.5
      - zipp==3.23.0
prefix: /home/testunot/miniconda3/envs/openpi
